KEYWORDS = [
    "Disasters",
    "Disaster Management",
    "Disaster Prevention",
    "Floods",
    "Fires",
    "Flooding",
    "Forecasting",
    "Flood Control",
    "Flood Risk Management",
    "Risk Assessment",
    "Risks Assessments",
    "Risk Analysis",
    "Risk Perception",   
    "Risk Factor",
    "Risk Factors",
    "Risk Identification",
    "Risk Mitigation",
    "Earthquakes",
    "Environmental Impact",
    "Environmental Management",
    "Environmental Protection",
    "Vulnerability",
    "Climate change",
]